apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "dbaas.redhat.com/v1alpha1",
          "kind": "RDSConnection",
          "metadata": {
            "name": "rdsconnection-sample",
            "namespace": "rds-sample"
          },
          "spec": {
            "instanceID": "rds-instance-sample",
            "inventoryRef": {
              "name": "rdsinventory-sample",
              "namespace": "rds-sample"
            }
          }
        },
        {
          "apiVersion": "dbaas.redhat.com/v1alpha1",
          "kind": "RDSInstance",
          "metadata": {
            "name": "rdsinstance-sample",
            "namespace": "rds-sample"
          },
          "spec": {
            "cloudProvider": "AWS",
            "cloudRegion": "us-east-1a",
            "inventoryRef": {
              "name": "rdsinventory-sample",
              "namespace": "rds-sample"
            },
            "name": "rds-instance-sample",
            "otherInstanceParams": {
              "AllocatedStorage": "20",
              "DBInstanceClass": "db.t3.micro",
              "DBInstanceIdentifier": "rds-instance-sample",
              "Engine": "postgres"
            }
          }
        },
        {
          "apiVersion": "dbaas.redhat.com/v1alpha1",
          "kind": "RDSInventory",
          "metadata": {
            "name": "rdsinventory-sample",
            "namespace": "rds-sample"
          },
          "spec": {
            "credentialsRef": {
              "name": "rds-credentials-sample",
              "namespace": "rds-sample"
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Database
    containerImage: quay.io/xiezhang/rds-dbaas-operator:v0.1.0
    description: RHODA Provider Operator for Amazon RDS.
    operatorframework.io/suggested-namespace: openshift-dbaas-operator
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/internal-objects: '["rdsconnections.dbaas.redhat.com","rdsinstances.dbaas.redhat.com","rdsinventories.dbaas.redhat.com"]'
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/RHEcosystemAppEng/rds-dbaas-operator
    support: dbaas-alpha-support@redhat.com
  name: rds-dbaas-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RDSConnection is the Schema for the rdsconnections API
      displayName: RDSConnection
      kind: RDSConnection
      name: rdsconnections.dbaas.redhat.com
      version: v1alpha1
    - description: RDSInstance is the Schema for the rdsinstances API
      displayName: RDSInstance
      kind: RDSInstance
      name: rdsinstances.dbaas.redhat.com
      version: v1alpha1
    - description: RDSInventory is the Schema for the rdsinventories API
      displayName: RDSInventory
      kind: RDSInventory
      name: rdsinventories.dbaas.redhat.com
      version: v1alpha1
  description: RHODA Provider Operator for Amazon RDS
  displayName: RHODA Provider Operator for Amazon RDS
  icon:
  - base64data: ""
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsconnections
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsconnections/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsconnections/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsinstances
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsinstances/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsinstances/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsinventories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsinventories/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - rdsinventories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rds.services.k8s.aws
          resources:
          - dbinstances
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - rds.services.k8s.aws
          resources:
          - dbinstances/finalizers
          verbs:
          - update
        - apiGroups:
          - services.k8s.aws
          resources:
          - adoptedresources
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: rds-dbaas-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: rds-dbaas-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
              type: rds-dbaas-operator
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
                type: rds-dbaas-operator
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: INSTALL_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/xiezhang7/rds-dbaas-operator:v0.1.0
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 20
                  periodSeconds: 20
                resources:
                  limits:
                    cpu: 200m
                    memory: 500Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: rds-dbaas-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: rds-dbaas-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - rds
  - dbaas
  links:
  - name: GitHub
    url: https://github.com/RHEcosystemAppEng/dbaas-dbaas-operator
  maintainers:
  - email: ecosystem-appeng@redhat.com
    name: Red Hat Ecosystem App Engineering
  maturity: alpha
  provider:
    name: Red Hat
    url: https://www.redhat.com
  replaces: rds-dbaas-operator.v0.1.0
  version: 0.1.0
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: rds-dbaas-operator-controller-manager
    failurePolicy: Fail
    generateName: vrdsinventory.kb.io
    rules:
    - apiGroups:
      - dbaas.redhat.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      resources:
      - rdsinventories
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-dbaas-redhat-com-v1alpha1-rdsinventory
