# permissions for end users to edit rdsconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdsconnection-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - rdsconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - rdsconnections/status
  verbs:
  - get
