# permissions for end users to edit rdsinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdsinventory-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - rdsinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - rdsinventories/status
  verbs:
  - get
