# permissions for end users to view rdsinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdsinstance-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - rdsinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - rdsinstances/status
  verbs:
  - get
