apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Database
    containerImage: controller:latest
    description: RHODA Provider Operator for Amazon RDS.
    operatorframework.io/suggested-namespace: openshift-dbaas-operator
    operators.operatorframework.io/internal-objects: '["rdsconnections.dbaas.redhat.com","rdsinstances.dbaas.redhat.com","rdsinventories.dbaas.redhat.com"]'
    repository: https://github.com/RHEcosystemAppEng/rds-dbaas-operator
    support: dbaas-alpha-support@redhat.com
  name: rds-dbaas-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RDSConnection is the Schema for the rdsconnections API
      displayName: RDSConnection
      kind: RDSConnection
      name: rdsconnections.dbaas.redhat.com
      version: v1alpha1
    - description: RDSInstance is the Schema for the rdsinstances API
      displayName: RDSInstance
      kind: RDSInstance
      name: rdsinstances.dbaas.redhat.com
      version: v1alpha1
    - description: RDSInventory is the Schema for the rdsinventories API
      displayName: RDSInventory
      kind: RDSInventory
      name: rdsinventories.dbaas.redhat.com
      version: v1alpha1
  description: RHODA Provider Operator for Amazon RDS
  displayName: RHODA Provider Operator for Amazon RDS
  icon:
  - base64data: ""
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - rds
  - dbaas
  links:
  - name: GitHub
    url: https://github.com/RHEcosystemAppEng/dbaas-dbaas-operator
  maintainers:
  - email: ecosystem-appeng@redhat.com
    name: Red Hat Ecosystem App Engineering
  maturity: alpha
  provider:
    name: Red Hat
    url: https://www.redhat.com
  replaces: rds-dbaas-operator.prior
  version: 0.0.0
